language: node_js
node_js:
  - 0.8

env:
  - BROWSER=Chrome-stable
  - BROWSER=Chrome-beta
  - BROWSER=Chrome-unstable
#  - BROWSER=PhantomJS
  - BROWSER=Firefox


before_install:
  - ./.travis-setup.sh
    
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - make

script:
  - ./node_modules/karma/bin/karma start ./karma/karma.conf.js --browsers $(echo $BROWSER | sed -e's/-.*//') --single-run
